### PR TITLE
refactoring the code

### PR DESCRIPTION
**Pull request by rpesche**
Hello,

I did refactor a little the code.
This refactoring aim to seperate the assembler code and the binding betwin token and corresponding machine code

### CODE REVIEW

**Comment by DanteFalzone0** [comment]
Thanks for your pr! Sorry I broke everything for a minute there ://

**Comment by DanteFalzone0** [comment]
It appears that my changes broke your tests, could you take a look at them and see about fixing it?

**Comment by rpesche** [comment]
Ok, I see the problem.
It's a change in program display.
I will create an issue and fix it as soon as possible

**Comment by DanteFalzone0** [comment]
Nevermind, I fixed it, but thank you :)

**Comment by DanteFalzone0** [comment]
On a more casual note, can I ask why you take interest in this project?

**Comment by rpesche** [comment]
Hum… at first it was to participate to the Hacktoberfest event from digital ocean.
I was searching for a project in python with lot of thing to do.

I found your project on a post on reddit.com/r/python and I found it cool :)

But now, I see a lot of thing to do, so I'm working more on make it better and more pythonic :)

**Comment by DanteFalzone0** [comment]
Ah okay. Well I hope you win one of the Hacktoberfest t-shirts, thanks for sharing :)

**Pull request merged**
